### ISSUE TITLE
Link : Game / Chat / User

### ISSUE THREAD

**Issue by williamollio** [williamollio/ft_transcendance#66]
**AC's** :
- [x] The user should be able to invite other users to play a Pong game through the chat
interface.
- [x] The user should be able to access other players profiles through the chat interface.
- [x] The user should be able to create dm chat  with other players.

**Comment by williamollio** [comment]
I will taking care of that : The user should be able to access other players profiles through the chat interface.

**Comment by hskowron** [comment]
Ok, great!
