### ISSUE TITLE
Stats - Improvements

### ISSUE THREAD

**Issue by williamollio** [williamollio/ft_transcendance#75]
- UI : improvements
- Test data : provide test data in the seed file
- Put text in translation file
- Search Field : use the common style of the TextFields components implemented

**Comment by hskowron** [comment]
> UI : improvements

What do you mean by that?

> Test data : provide test data in the seed file
Put text in translation file

Done

> Search Field : use the common style of the TextFields components implemented

Also not sure what you mean by that. Do we have a common style defined for our project?

**Comment by hskowron** [comment]
It's looking better now, we still wanted to put the personal stats on the profile page but all of the stuff above has been done.
