### ISSUE TITLE
Chats - Improvements

### ISSUE THREAD

**Issue by williamollio** [williamollio/ft_transcendance#76]
- Room created gets deleted when the browser is refreshed (sometimes). But messages within the rooms are always gone
- Put text in translation file

**Comment by hskowron** [comment]
> Room created gets deleted when the browser is refreshed (sometimes)
I can't seem to replicate that issue, do you have more info on what causes this for you?

> But messages within the rooms are always gone
I now also get the messages from the BE on refresh, so this is now fixed

**Comment by hskowron** [comment]
>Room created gets deleted when the browser is refreshed (sometimes)

I found the issue, I will push the fix on my next PR
